server:
  port: 28080

# Logging
logging:
  file:
    name: /data/logs/app.log

# SFE4J configuration
sfe4j:
  base-dir-path: ${BASE_DIR_PATH:/}
  restrict-to-base-dir: ${RESTRICT_TO_BASE_DIR:false}
  title: ${TITLE:SFE4J}
  description: ${DESCRIPTION:Simple File Explorer for spring-boot based Java Web Application.}
  quick-links:
    root: /
    logs: /data/logs