server:
  port: 8080

spring:
  application:
    name: "sfe4j-demo"
  boot:
    admin:
      client:
        url: https://spring-boot-admin.amoylabs.com:30443
        instance:
          service-base-url: https://sfe4j-demo.amoylabs.com:30443

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# SFE4J configuration
sfe4j:
  base-dir-path: "/data"
  restrict-to-base-dir: false
  title: "SFE4J Demo"
  description: "Simple File Explorer for spring-boot based Java Web Application."
  quick-links:
    root: /
    logs: /data/logs

# Logging
logging:
  file:
    name: /data/logs/app.log
